CREATE TABLE covers (
    id INTEGER PRIMARY KEY AUTOINCREMENT ,
    name VARCHAR(256) NOT NULL,
    mime_type VARCHAR(256) NOT NULL,
    md5_hash VARCHAR(256) NOT NULL
);

CREATE TABLE books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(256) NOT NULL,
    description VARCHAR(256) NOT NULL,
    year INTEGER NOT NULL,
    publisher VARCHAR(256) NOT NULL,
    author VARCHAR(256) NOT NULL,
    pages INTEGER NOT NULL,
    cover_id INTEGER NOT NULL,
    FOREIGN KEY (cover_id) REFERENCES covers(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE genres (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE book_to_genres (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    book_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    FOREIGN KEY (book_id) REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(256) NOT NULL,
    description VARCHAR(256) NOT NULL
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    login VARCHAR(256) NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    surname VARCHAR(256) NOT NULL,
    name VARCHAR(256) NOT NULL,
    lastname VARCHAR(256),
    role_id INTEGER NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    book_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(256) NOT NULL,
    date_created DATE NOT NULL DEFAULT (CURRENT_DATE),
    FOREIGN KEY (book_id) REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);